Hardcode tgui script name instead of using $0 (#47553)

diff --git a/tgui-next/bin/tgui b/tgui-next/bin/tgui
--- a/tgui-next/bin/tgui
+++ b/tgui-next/bin/tgui
@@ -18,6 +18,73 @@ if [[ ${1} == "--clean" ]]; then
   rm -rf packages/tgui/public/.tmp
   rm -rf **/node_modules
   rm -f **/package-lock.json
+<<<<<<< HEAD
+=======
+}
+
+## Validates current build against the build stored in git
+task-validate-build() {
+  cd "${base_dir}"
+  local diff
+  diff="$(git diff packages/tgui/public/tgui.bundle.*)"
+  if [[ -n ${diff} ]]; then
+    echo "Error: our build differs from the build committed into git."
+    echo "Please rebuild tgui."
+    exit 1
+  fi
+  echo "tgui: build is ok"
+}
+
+## Installs merge drivers and git hooks
+task-install-git-hooks() {
+  cd "${base_dir}"
+  local git_root
+  local git_base_dir
+  git_root="$(git rev-parse --show-toplevel)"
+  git_base_dir="${base_dir/${git_root}/.}"
+  git config --replace-all merge.tgui-merge-bundle.driver \
+    "${git_base_dir}/bin/tgui --merge=bundle %O %A %B %L"
+  echo "tgui: Merge drivers have been successfully installed!"
+}
+
+## Bundle merge driver
+task-merge-bundle() {
+  local file_ancestor="${1}"
+  local file_current="${2}"
+  local file_other="${3}"
+  local conflict_marker_size="${4}"
+  echo "tgui: Discarding a local tgui build"
+  ## Do nothing (file_current will be merged and is what we want to keep).
+  exit 0
+}
+
+
+## Main
+## --------------------------------------------------------
+
+if [[ ${1} == "--merge"* ]]; then
+  if [[ ${1} == "--merge=bundle" ]]; then
+    shift 1
+    task-merge-bundle "${@}"
+  fi
+  echo "Unknown merge strategy: ${1}"
+  exit 1
+fi
+
+if [[ ${1} == "--install-git-hooks" ]]; then
+  shift 1
+  task-install-git-hooks
+  exit 0
+fi
+
+## Continuous integration scenario
+if [[ ${1} == "--ci" ]]; then
+  task-clean
+  task-install
+  task-eslint
+  task-webpack --mode=production
+  task-validate-build
+>>>>>>> 4c71511256... Hardcode tgui script name instead of using $0 (#47553)
   exit 0
 fi
 
